# Generated by Django 5.0.6 on 2024-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('letter_number', models.CharField(max_length=50)),
                ('agenda_number', models.CharField(blank=True, max_length=50)),
                ('letter_date', models.DateField()),
                ('received_date', models.DateField()),
                ('file', models.FileField(upload_to='upload/')),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
